# Stage 1
FROM node:16.14 as react-build
WORKDIR /app

ARG REACT_APP_PAYPAL_CLIENT_ID
ARG REACT_APP_STRIPE_PUBLIC_KEY
ARG REACT_APP_STRIPE_SECRET_KEY
ARG REACT_APP_STRIPE_SUCCESS_URL
ARG REACT_APP_ALGOLIA_APP_ID
ARG REACT_APP_ALGOLIA_SEARCH_KEY
ARG REACT_APP_ALGOLIA_INDEX_NAME

ENV REACT_APP_PAYPAL_CLIENT_ID=$REACT_APP_PAYPAL_CLIENT_ID
ENV REACT_APP_STRIPE_PUBLIC_KEY=$REACT_APP_STRIPE_PUBLIC_KEY
ENV REACT_APP_STRIPE_SECRET_KEY=$REACT_APP_STRIPE_SECRET_KEY
ENV REACT_APP_STRIPE_SUCCESS_URL=$REACT_APP_STRIPE_SUCCESS_URL
ENV REACT_APP_ALGOLIA_APP_ID=$REACT_APP_ALGOLIA_APP_ID
ENV REACT_APP_ALGOLIA_SEARCH_KEY=$REACT_APP_ALGOLIA_SEARCH_KEY
ENV REACT_APP_ALGOLIA_INDEX_NAME=$REACT_APP_ALGOLIA_INDEX_NAME

COPY . ./
RUN npm install
RUN npm run build

# Stage 2 - the production environment
FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=react-build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
